### ISSUE TITLE
Enable tags or categories for predictions

### ISSUE THREAD

**Issue by LoadingScreen** [bellroy/predictionbook#130]
Predicting my own actions feels different than predicting the actions of heads of state. I expect this to have an effect on my calibration. Maybe I am underconfident about current events and overconfident when it comes to project deadlines.
I want to be able to tag predictions, and then view my calibration filtered by tag.

**Comment by Raemon** [comment]
I'd also really like tags. There are usually a couple different types of tags I might want:

1) self-predictions (like LoadingScreen mentions above)
2) predictions for the org I work at (i.e. will my team decide to do X? Will our new product get at least 100 users by the end of the week?)
3) off-the-cuff predictions vs carefully thought through predictions. (the actual motivating example for me thinking about this today was wanting to two predictions, and start tracking whether my off-the-cuff instinct was more or less accurate than my carefully considered guess)
4) different topics (politics, covid, community drama, etc)

Being able to filter on different types of predictions feels pretty useful to me. I'd personally be willing to pay at least $1000 for the dev time and likely more.

**Comment by jaysonvirissimo** [comment]
There are three basic solutions to this kind of problem, each with different tradeoffs:
* Users could create **tags** which are arbitrary strings, two of which would be considered identical if they are exact matches (perhaps ignoring case). This is the most flexible solution and could handle a great number of use applications. On the other hand, letting users create tags willy-nilly could result in spam, which would require manual cleanup (perhaps by an admin). Also, calculating separate Brier scores for each user for every tag could lead to performance issues (although, this could be mitigated by only calculating those that a user specifically opts-in for).
* Another option is to use **categories** or a predefined list which could be used to group predictions along a common theme. This wouldn't result in any performance issues or need for manual cleanup of spam, but is far less flexible than tags, so wouldn't cover all the mentioned use cases. It would also require us to decide up front what the categories should be, rather than on the users themselves.
* Another possibility is prediction **types**, or having separate models for predictions that might have a different data structure or behavior. For example, some predictions could require external, publicly verifiable, sources in order to be judged correct/incorrect, but "personal" predictions would only need the say-so of the original predictor. This solution is the least flexible, but also potentially the most powerful.

IMO, the tags solutions would best handle @Raemon's 4 desiderata.
